version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "127.0.0.1:5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
